# Generated by Django 4.0.1 on 2022-01-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdb_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('year', models.CharField(max_length=16)),
                ('genre', models.CharField(max_length=40)),
                ('director', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50)),
                ('actors', models.CharField(max_length=100)),
                ('plot', models.TextField()),
                ('rating', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
