apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: criticapp-web
  namespace: criticapp
  labels:
    app: criticapp-web
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: criticapp-web
  namespaceSelector:
    matchNames:
      - criticapp
  endpoints:
    - port: http
      path: /metrics/
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        - targetLabel: __address__
          replacement: criticapp-web.criticapp.svc.cluster.local:80
