# Generated by Django 4.0.2 on 2022-02-11 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('item_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('year', models.CharField(max_length=10)),
                ('attr1', models.CharField(max_length=120)),
                ('attr2', models.CharField(max_length=120)),
                ('attr3', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('rating', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_rating', models.FloatField()),
                ('review_data', models.TextField(null=True)),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.reviewitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
