# Generated by Django 4.0.2 on 2022-03-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_tags',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
