# Generated by Django 4.0.3 on 2022-03-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_review_tags'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'review_item'), name='unique review'),
        ),
    ]
