# Generated by Django 4.2.7 on 2023-11-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='attr1',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='attr2',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='attr3',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
