# Generated by Django 4.0.2 on 2022-02-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('item_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('year', models.CharField(max_length=10)),
                ('attr1', models.CharField(max_length=120)),
                ('attr2', models.CharField(max_length=120)),
                ('attr3', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('rating', models.CharField(max_length=5)),
            ],
        ),
    ]
