# Generated by Django 4.0.2 on 2022-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
    ]
